apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-deployment
  labels:
    app: prediction-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-micro
  template:
    metadata:
      labels:
        app: prediction-micro
    spec:
      containers:
      - name:  prediction-backend
        image: houssem28/ecopact_prediction_service:15
        ports:
        - containerPort: 3004
        env:
            - name: DB_URI
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: JWT_SECRET
      volumes:
         - name: shared-storage
           persistentVolumeClaim:
             claimName: prediction-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: prediction
spec:
  selector:
    app: prediction-micro
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004