apiVersion: v1
kind: Secret
metadata:
  name: secret-data
type: Opaque
data:
  JWT_SECRET: MDEyZmUwOTQ1MDY1NjEyNGMwNTg1ZTIwYjc2NDc3NDJjMDVkNDgyZDI2M2YyMGEzNTQ5NThhY2NlNjY5MTkyMQ==
  APP_EMAIL_ADRESS: YWNocmVmaDFibGkyMkBnbWFpbC5jb20=
  APP_EMAIL_PASSWORD: ZmNociBxaWlsIGFjd3ggdGVxdw==
  APP_EMAIL_ADRESS_RECEIVER: YWNocmVmaDFibGkyMkBnbWFpbC5jb20=
 
